config/routes.rb
Rails.application.routes.draw do
  resources :charges
  root to: 'charges#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "Ben's 3D Printer Monitor"
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def index
	end

	def hello
		render html: "Ben's 3D Printer Monitor (from charges controller)"
	end

	def create
		#amount in cents
		@amount = 2500
		customer = Stripe::Customer.create(
			:email => 'customer@ben.customer',
			:card => params[:stripeToken]
		)

		charge = Stripe::Charge.create(
			:customer		 	=> customer.id,
			:amount				=> @amount,
			:description	=> 'Ben\'s 3D Printer Monitor',
			:currency			=> 'usd'
		)

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to charges_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%=@amount/100%></strong> for a great device.</h2>
<br>
<%= link_to "main page", charges_path %>

app/views/charges/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>BenAppIndexHeadTitle</title>
</head>
<body>
<h2 style="text-align: center;">Ben's 3D Printer Monitor:</h2>
<div class="content">
<br><br>
<%=image_tag("https://images-na.ssl-images-amazon.com/images/I/41Hkag9%2B%2B0L._SX466_.jpg") %>
<br><br>
</div>
<br><br>

<div class="morecontent">
<%= link_to "buy this product", new_charge_path %>
</div>
</body>
<footer>
  <br>
  <p>Contact information: <a href="mailto:ourcontactinfo@example.com">
  ourcontactinfo@example.com</a>.</p>
</footer>
</html>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
	<article>
		<label class="amount">
			<span>Amount: $25.00</span>
		</label>
		<br><br>
	</article>

	<script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
					data-key="<%=Rails.configuration.stripe[:publishable_key] %>"
					data-description="One 3D Printer Monitor"
					data-amount="2500"></script>
<% end %>
<br>
<%= link_to "main page", charges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BenApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>